v 10!

diff --git a/playcurl/system/bin/fpd b/playcurl/system/bin/fpd
--- a/playcurl/system/bin/fpd
+++ b/playcurl/system/bin/fpd
@@ -1,1 +1,14 @@
-/system/bin/curl -L "https://raw.githubusercontent.com/daboynb/PlayIntegrityNEXT/main/Fp_Downloader.apk%20to%20use%20with%20play%20integrity%20by%20chiteroman/fpd.sh" -o /storage/emulated/0/fpd.sh > /dev/null 2>&1 || /system/bin/curl -L "https://raw.githubusercontent.com/daboynb/PlayIntegrityNEXT/main/Fp_Downloader.apk%20to%20use%20with%20play%20integrity%20by%20chiteroman/fpd.sh" -o /storage/emulated/0/fpd.sh && /system/bin/sh /storage/emulated/0/fpd.sh
+script_url="https://raw.githubusercontent.com/daboynb/PlayIntegrityNEXT/main/Fp_Downloader.apk%20to%20use%20with%20play%20integrity%20by%20chiteroman/fpd.sh"
+
+local_script_path="/storage/emulated/0/fpd.sh"
+
+# Download the script 
+/system/bin/curl -L "$script_url" -o "$local_script_path" > /dev/null 2>&1
+
+# Check if the download was successful 
+if [ $? -eq 0 ]; then
+    echo "Download successful. Executing the script..."
+    /system/bin/sh "$local_script_path"
+else
+    echo "Download failed. Please check the URL and network connection."
+fi
